spring.application.name=project-loop-backend
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/loop_db
spring.datasource.username=postgres
spring.datasource.password=Shahu@123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080